
name: task4

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build
      run: |
        apt install git
        cd TP_task4_test
        mkdir 3rdparty
        

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
