
name: task4

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build
      run: |
        mkdir 3rdparty
        mkdir build
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        GOOGLE_TEST_DIR=googletest
        echo $GOOGLE_TEST_DIR
        cd ../build
        cmake ..
        
        

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
