
name: task4

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir 3rdparty
        mkdir build
        mkdir output
        INSTALL_PREFIX=$(pwd)/output
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        cd ../build
        GOOGLE_TEST_DIR=googletest cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX ..
        make
        make install
        ls -la bin/
        
#     - uses: akhtyamovpavel/ActionGtestReport@v0.0.9
#       with: 
      
#     - name: Test
        

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
