
name: task4

on: [push]

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir 3rdparty
        mkdir build
        mkdir output
        MAIN_DIR=$(pwd)
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        cd ../build
        GOOGLE_TEST_DIR=googletest cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX/output ..
        make
        make install
        
        
    - uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with: 
        exec-path:  /home/runner/work/TP_task4_test/TP_task4_test/build/bin/CTestExe
        report-path: /home/runner/work/TP_task4_test/TP_task4_test/akhtyamovpavel-output
        working-directory: /home/runner/work/TP_task4_test/TP_task4_test/
      
    - name: Test
      run : |
        ls -la bin/
